---
name: setup
description: Setup Node.js and pnpm

runs:
  using: composite
  steps:
    - name: 🌎 Setup Node.js
      uses: actions/setup-node@v4
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
      with:
        node-version-file: package.json
        cache: npm

    - name: 📦 Install Dependencies
      run: npm ci --prefer-offline --no-audit --no-fund
      shell: bash
