name: "Solana Payout Action"
description: "Automatically pay SOL/SPL tokens to a specified recipient wallet address in Solana"
author: "UraniumCorporation"
branding:
  icon: "box"
  color: "green"
inputs:
  recipient-wallet-address:
    description: "Solana wallet address of the recipient"
    required: true
  token:
    description: "Token to send - either 'SOL' or an SPL token address"
    required: true
  amount:
    description: "Amount to send (in SOL or tokens)"
    required: true
  network:
    description: "Solana network to use (mainnet-beta, devnet, testnet)"
    required: false
    default: "mainnet-beta"
  timeout:
    description: "Timeout to confirm the transaction in milliseconds"
    required: false
    default: 300000
outputs:
  success:
    description: "Whether the payment was successful"
  error:
    description: "The error that occurred during the payment"
  transaction:
    description: "The transaction signature for the successful payment"
runs:
  using: "node20"
  main: "dist/index.js"
