---
name: 💰 Solana Payout Action
run-name: "💰 Solana Payout Action - Manually Triggered by @${{ github.actor }}"
on:
  # Manual trigger with inputs
  workflow_dispatch:
    inputs:
      recipient:
        description: "Recipient wallet address"
        required: true
      amount:
        description: "Amount to send (in SOL or tokens)"
        required: true
        default: "0.1"
      token:
        description: "Token to send - either 'SOL' or an SPL token address"
        required: true
        default: "SOL"
      network:
        description: "Solana network (mainnet-beta, devnet, testnet)"
        required: true
        default: "devnet"
        type: choice
        options:
          - mainnet-beta
          - devnet
          - testnet
      timeout:
        description: "Timeout to confirm the transaction in milliseconds"
        required: false
        default: 300000
        type: number

permissions:
  contents: read # Needed for the checkout action

jobs:
  solana-payout:
    name: 💰 Solana Payout Action
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 💰 Solana Payout Action
        uses: ./ # Uses the action in the root directory
        id: payout
        continue-on-error: true
        with:
          recipient-wallet-address: ${{ inputs.recipient }}
          amount: ${{ inputs.amount }}
          network: ${{ inputs.network }}
          token: ${{ inputs.token }}
          timeout: ${{ inputs.timeout }}
        env:
          SENDER_WALLET_SECRET: ${{ secrets.SENDER_WALLET_SECRET }}

      - name: 🪵 Log Solana Payout Action Outputs
        run: |
          echo "Success: ${{ steps.payout.outputs.success }}"
          echo "Error: ${{ steps.payout.outputs.error }}"
          echo "Transaction: ${{ steps.payout.outputs.transaction }}"

      - name: 🪵 Log Payout Results
        run: |
          if [[ "${{ steps.payout.outputs.success }}" == "true" ]]; then
            echo "✅ Payment successful!"
          else
            echo "❌ Payment failed:"
            echo "${{ steps.payout.outputs.error }}"
            exit 1
          fi
